name: Build2 EXE with PyInstaller

on:                       # When to run
  push:                   #  every push to any branch
  pull_request:

jobs:
  build-win:
    runs-on: windows-latest        # 1 CPU Windows Server runner
    steps:
    - uses: actions/checkout@v4    # Pulls your code

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'     # Pick the runtime you use locally

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build EXE
      run: pyinstaller --onefile "UnprotectExcel v1.py"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: unlock_excel_exe
        path: "dist/UnprotectExcel v1.exe"
